import test from "node:test";
import assert from "node:assert/strict";
import { renderUiHtml } from "../src/core/ui.js";

test("renderUiHtml returns a single-file UI html", () => {
  const html = renderUiHtml({ title: "rmemo", apiBasePath: "" });
  assert.ok(html.startsWith("<!doctype html>"));
  assert.ok(html.includes("rmemo UI"));
  assert.ok(html.includes("/status?format=json"));
  assert.ok(html.includes("/search?mode=semantic"));
  assert.ok(html.includes("/focus?q="));
  assert.ok(html.includes("/events"));
  assert.ok(html.includes("/events/export"));
  assert.ok(html.includes("/diagnostics/export"));
  assert.ok(html.includes("/embed/status"));
  assert.ok(html.includes("/embed/plan"));
  assert.ok(html.includes("/embed/build"));
  assert.ok(html.includes("embedParallelism"));
  assert.ok(html.includes("embedBatchDelayMs"));
  assert.ok(html.includes("/embed/jobs"));
  assert.ok(html.includes("/embed/jobs/config"));
  assert.ok(html.includes("/embed/jobs/failures"));
  assert.ok(html.includes("/embed/jobs/retry-failed"));
  assert.ok(html.includes("/embed/jobs/governance"));
  assert.ok(html.includes("/embed/jobs/governance/config"));
  assert.ok(html.includes("/embed/jobs/governance/apply"));
  assert.ok(html.includes("/embed/jobs/governance/history"));
  assert.ok(html.includes("/embed/jobs/governance/rollback"));
  assert.ok(html.includes("/embed/jobs/governance/simulate"));
  assert.ok(html.includes("/embed/jobs/\" + encodeURIComponent(id) + \"/retry"));
  assert.ok(html.includes("embedPriority"));
  assert.ok(html.includes("embedRetryTemplate"));
  assert.ok(html.includes("embedMaxRetries"));
  assert.ok(html.includes("embedRetryDelayMs"));
  assert.ok(html.includes("embedJobsMaxConcurrent"));
  assert.ok(html.includes("retryFailedLimit"));
  assert.ok(html.includes("embedFailureClass"));
  assert.ok(html.includes("embedClusterKey"));
  assert.ok(html.includes("govEnabled"));
  assert.ok(html.includes("govWindow"));
  assert.ok(html.includes("govFailureRateHigh"));
  assert.ok(html.includes("govVersionId"));
  assert.ok(html.includes("govSimMode"));
  assert.ok(html.includes("embed:job:progress"));
  assert.ok(html.includes("embed:job:retry"));
  assert.ok(html.includes("embed:job:requeued"));
  assert.ok(html.includes("embed:jobs:retry-failed"));
  assert.ok(html.includes("embed:jobs:governance:action"));
  assert.ok(html.includes("embed:jobs:governance:skip"));
  assert.ok(html.includes("embed:jobs:governance:versioned"));
  assert.ok(html.includes("embed:jobs:governance:rollback"));
  assert.ok(html.includes("embed:jobs:config"));
  assert.ok(html.includes("embed:build:progress"));
  assert.ok(html.includes("/refresh"));
  assert.ok(html.includes("/watch"));
  // Should not embed tokens.
  assert.ok(!html.toLowerCase().includes("rmemo_token="));
});
