import test from "node:test";
import assert from "node:assert/strict";
import { renderUiHtml } from "../src/core/ui.js";

test("renderUiHtml returns a single-file UI html", () => {
  const html = renderUiHtml({ title: "rmemo", apiBasePath: "" });
  assert.ok(html.startsWith("<!doctype html>"));
  assert.ok(html.includes("rmemo UI"));
  assert.ok(html.includes("/status?format=json"));
  assert.ok(html.includes("/search?mode=semantic"));
  assert.ok(html.includes("/focus?q="));
  assert.ok(html.includes("/ws/list"));
  assert.ok(html.includes("/ws/focus?q="));
  assert.ok(html.includes("/ws/focus/snapshots"));
  assert.ok(html.includes("/ws/focus/compare"));
  assert.ok(html.includes("/ws/focus/report"));
  assert.ok(html.includes("/ws/focus/reports"));
  assert.ok(html.includes("/ws/focus/report-item"));
  assert.ok(html.includes("/ws/focus/trends"));
  assert.ok(html.includes("/ws/focus/trend"));
  assert.ok(html.includes("/ws/focus/alerts"));
  assert.ok(html.includes("/ws/focus/alerts/config"));
  assert.ok(html.includes("/events"));
  assert.ok(html.includes("/events/export"));
  assert.ok(html.includes("/diagnostics/export"));
  assert.ok(html.includes("/embed/status"));
  assert.ok(html.includes("/embed/plan"));
  assert.ok(html.includes("/embed/build"));
  assert.ok(html.includes("embedParallelism"));
  assert.ok(html.includes("embedBatchDelayMs"));
  assert.ok(html.includes("/embed/jobs"));
  assert.ok(html.includes("/embed/jobs/config"));
  assert.ok(html.includes("/embed/jobs/failures"));
  assert.ok(html.includes("/embed/jobs/retry-failed"));
  assert.ok(html.includes("/embed/jobs/governance"));
  assert.ok(html.includes("/embed/jobs/governance/config"));
  assert.ok(html.includes("/embed/jobs/governance/apply"));
  assert.ok(html.includes("/embed/jobs/governance/history"));
  assert.ok(html.includes("/embed/jobs/governance/rollback"));
  assert.ok(html.includes("/embed/jobs/governance/simulate"));
  assert.ok(html.includes("/embed/jobs/governance/benchmark"));
  assert.ok(html.includes("/embed/jobs/governance/benchmark/adopt"));
  assert.ok(html.includes("/embed/jobs/\" + encodeURIComponent(id) + \"/retry"));
  assert.ok(html.includes("embedPriority"));
  assert.ok(html.includes("embedRetryTemplate"));
  assert.ok(html.includes("embedMaxRetries"));
  assert.ok(html.includes("embedRetryDelayMs"));
  assert.ok(html.includes("embedJobsMaxConcurrent"));
  assert.ok(html.includes("retryFailedLimit"));
  assert.ok(html.includes("embedFailureClass"));
  assert.ok(html.includes("embedClusterKey"));
  assert.ok(html.includes("govEnabled"));
  assert.ok(html.includes("govWindow"));
  assert.ok(html.includes("govFailureRateHigh"));
  assert.ok(html.includes("govVersionId"));
  assert.ok(html.includes("govSimMode"));
  assert.ok(html.includes("govBenchMode"));
  assert.ok(html.includes("wsOnly"));
  assert.ok(html.includes("loadWsList"));
  assert.ok(html.includes("doWsFocus"));
  assert.ok(html.includes("wsSaveSnapshot"));
  assert.ok(html.includes("wsCompareLatest"));
  assert.ok(html.includes("wsTag"));
  assert.ok(html.includes("loadWsSnapshots"));
  assert.ok(html.includes("wsFromId"));
  assert.ok(html.includes("wsToId"));
  assert.ok(html.includes("doWsCompare"));
  assert.ok(html.includes("doWsReport"));
  assert.ok(html.includes("wsSaveReport"));
  assert.ok(html.includes("wsReportTag"));
  assert.ok(html.includes("loadWsReports"));
  assert.ok(html.includes("wsReportId"));
  assert.ok(html.includes("showWsReport"));
  assert.ok(html.includes("loadWsTrends"));
  assert.ok(html.includes("wsTrendKey"));
  assert.ok(html.includes("showWsTrend"));
  assert.ok(html.includes("loadWsAlerts"));
  assert.ok(html.includes("loadWsAlertsConfig"));
  assert.ok(html.includes("runWsAlertsAuto"));
  assert.ok(html.includes("saveWsAlertsConfig"));
  assert.ok(html.includes("govBenchmarkAutoAdoptEnabled"));
  assert.ok(html.includes("govBenchmarkMinScore"));
  assert.ok(html.includes("govBenchmarkMinGap"));
  assert.ok(html.includes("embed:job:progress"));
  assert.ok(html.includes("embed:job:retry"));
  assert.ok(html.includes("embed:job:requeued"));
  assert.ok(html.includes("embed:jobs:retry-failed"));
  assert.ok(html.includes("embed:jobs:governance:action"));
  assert.ok(html.includes("embed:jobs:governance:skip"));
  assert.ok(html.includes("embed:jobs:governance:versioned"));
  assert.ok(html.includes("embed:jobs:governance:rollback"));
  assert.ok(html.includes("embed:jobs:benchmark:adopt"));
  assert.ok(html.includes("embed:jobs:benchmark:skip"));
  assert.ok(html.includes("embed:jobs:config"));
  assert.ok(html.includes("embed:build:progress"));
  assert.ok(html.includes("/refresh"));
  assert.ok(html.includes("/watch"));
  // Should not embed tokens.
  assert.ok(!html.toLowerCase().includes("rmemo_token="));
});
